### ISSUE TITLE
Sdk implement system 

### ISSUE THREAD

**Issue by ghost** [goostengine/goost#184]
Please add a system so that we can add sdk in our android godot game. This feature is very much important for Android game developer. Because are are too many google service that can be implement via there sdk. Please 🥺🙏 🥺🥺 add this system.

**Comment by Xrayez** [comment]
I'm sorry but it's not clear to me what exactly you'd like to see in Goost, especially when I'm not familiar with Android development. In any case, I think that's not something which is in alignment with neither Godot nor Goost development due to open-source philosophy, and there may be other legal reasons.

Unfortunately, we're currently in the state of war with Russia, so I may be slow to respond (writing from a bomb shelter at the moment).

**Comment by ghost** [comment]
> I'm sorry but it's not clear to me what exactly you'd like to see in Goost, especially when I'm not familiar with Android development. In any case, I think that's not something which is in alignment with neither Godot nor Goost development due to open-source philosophy, and there may be other legal reasons.
> 
> Unfortunately, we're currently in the state of war with Russia, so I may be slow to respond (writing from a bomb shelter at the moment).

🥺🥺🥺🥺
