### ISSUE TITLE
ShapeCast2D.get_collision_* returns stale data when `cast_to` is non-zero and no collision occurs on a frame

### ISSUE THREAD

**Issue by Aloshi** [goostengine/goost#47]
Hey there, first off thanks for building this - it saved me a ton of time on my project! 😄

## Problem
I ran into an issue where `ShapeCast2D.get_collision_count()` and friends seem to be returning stale information when `cast_to` is non-zero and no collision occurred on a frame. I'm doing something like:

```gdscript
func _physics_process(delta):
	$ShapeCast2D.cast_to = motion
	if motion == Vector2.ZERO:
		return

	$ShapeCast2D.force_shapecast_update()
	for i in $ShapeCast2D.get_collision_count():
		var normal = $ShapeCast2D.get_collision_normal(i)
		# ...
```

And noticed the for loop would still run when there was nothing around to collide with, and I was seeing stale data in `normal`. I worked around this by checking `$ShapeCast2D.is_colliding()` before the loop, but this caught me off guard.

## Suggestion

Some documentation calling this out if this is intended behavior. If it's not, I think calling `result.clear();` regardless of `process_intersections` might solve the problem: 
https://github.com/goostengine/goost/blob/b0e5d49ddf835570c814f184751fac6b52a72177/scene/physics/2d/shape_cast_2d.cpp#L247-L275

**Comment by Xrayez** [comment]
At first I thought that's how `RayCast2D` actually works, but turns out it's not the case. #48 should fix this, thanks for reporting!

And the documentation is also right about this, it's just that I've mostly copy-pasted `RayCast2D` documentation and adapted to `ShapeCast2D` functionality while I worked on this (feature-wise it should be close to `RayCast2D`).

**Comment by Aloshi** [comment]
Awesome, thanks for the quick fix!
